stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Building the project..."

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - chmod +x script/run_tests.sh
    - ./script/run_tests.sh